```{r}
library(tidyverse)
library(here)

international <- c(
  "australia",
  "new_zealand",
  "england",
  "south_africa",
  "ireland",
  "italy",
  "japan",
  "scotland",
  "wales",
  "france",
  "argentina",
  "georgia",
  "fiji",
  "romania",
  "usa",
  "tonga",
  "russia",
  "namibia",
  "samoa",
  "uruguay",
  "canada"
)
```

```{r}
team_table <- read_csv(here("5_clean_data/team_data.csv")) %>%
  pivot_wider(names_from = stat, values_from = values) %>%
  select(-match_id) %>%
  mutate(
    type_of_team = if_else(team %in% international,
      "international", "club"
    ),
    .after = team
  ) %>%
  mutate(
    hemisphere = case_when(
      competition %in% c(
        "autumn_nations_cup",
        "european_champions_cup",
        "premiership",
        "premiership_cup",
        "pro_14", "six_nations",
        "top_14"
      ) ~ "northern",
      competition %in% c(
        "internationals",
        "rugby_world_cup"
      ) ~ "mixed",
      TRUE ~ "southern"
    ),
    .after = competition
  )
international_team_matches <- team_table %>% 
  filter(type_of_team == "international")

club_team_matches <- team_table %>% 
  filter(type_of_team == "club")
```
